# Generated by Django 5.1.7 on 2025-03-13 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area_utilizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_area', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aberto', 'aberto'), ('Fechado', 'fechado')], max_length=50)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_unidade', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.area_utilizacao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento.tipo_material')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento.unidade_medida')),
            ],
        ),
        migrations.CreateModel(
            name='Itens_lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento.itens')),
                ('lista_planejamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planejamento.lista_planejamento')),
            ],
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('setor_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planejamento.setores')),
            ],
        ),
        migrations.AddField(
            model_name='lista_planejamento',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento.setores'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha_hash', models.CharField(max_length=255)),
                ('perfil', models.CharField(default='padrao', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento.setores')),
            ],
        ),
        migrations.AddField(
            model_name='lista_planejamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planejamento.usuario'),
        ),
    ]
